<a href="https://colab.research.google.com/github/acubillosunal/UBM-MACHINE-LEARNING-1/blob/main/04-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras alamancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

# **Numpy**

Esta biblioteca, cuyo nombre significa numerical Python, constituye el núcleo de muchas otras bibliotecas de Python que se han originado a partir de ella. De hecho, NumPy es la biblioteca básica para la computación científica en Python, ya que proporciona estructuras de datos y funciones de alto rendimiento que el paquete básico de Python no proporciona.

NumPy es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

## Importar la libreria NumPy

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])

In [ ]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
from math import sin

seno = []
for i in [1,2,3]:
    seno.append(sin(i))
seno


[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [ ]:
x = np.array([[1,2,3], [4,5,6]])

In [ ]:
y = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

## **Creación intrinseca de arreglos**

La biblioteca NumPy proporciona un conjunto de funciones que generan ndarrays con contenido inicial, creados con diferentes valores según la función.



In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3,3))

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(4,10)

In [ ]:
np.arange(0,12,3)

## **Operaciones básicas**

In [ ]:
a = np.arange(0,4)

## **Matrices vs Arrreglos**


## **Funciones universales**

In [ ]:
a = np.arange(1,6)


In [ ]:
np.sqrt(a)

In [ ]:
np.log(a)

In [ ]:
np.cos(a)

## **Agregar funciones**

In [ ]:
a = 5*np.random.random(5)+1

## **Indexando**

In [ ]:
a = np.arange(10, 16)

In [ ]:
A = np.arange(10,19).reshape((3,3))

In [ ]:
A[1,2]

## **Slicing**


In [ ]:
a = np.arange(10,16)

In [ ]:
a[1:4]

In [ ]:
a[1:5:2]

In [ ]:
a[::2]

In [ ]:
a[:5:2]

array([10, 12, 14])

In [ ]:
a[:5:]

array([10, 11, 12, 13, 14])

In [ ]:
b = np.arange(10,31)

In [ ]:
A = np.arange(10,19).reshape((3,3))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## **Condicionales y arreglos Booleanos**

In [ ]:
A = np.random.random((4,4))

# **Referencias**

[1]. https://es.wikipedia.org/wiki/NumPy

[2]. Unpingo J. Python for Probability, Statistics and Machine Learning. Second Edition. Ed.
Springer.

[3]. Nelli F. Python Data Analytics. With Pandas, NumPy and Matplotlib. Second Ed.