<a href="https://colab.research.google.com/github/Ambg0231/MachineLearningNotes/blob/main/Taller1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Nombres**

* *Angela María Burgos*
* *Sandra Beatriz Escobar*



# **Taller Numpy**



1) Importar la libreria numpy y ver la versión que se está usando

In [ ]:
import numpy as np

# Ver la versión de NumPy
print(np.__version__)

1.25.2


2) Crear un arreglo de tamaño 1D desde 10 hasta 30

In [ ]:
a1_np = np.arange(10, 31)
print(a1_np)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


3) Crear un arreglo booleano con valor True de tamaño 4x4

In [ ]:
bool_ar = np.ones((4, 4), dtype=bool)
print(bool_ar)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


4) Generar un arreglo desde el 10 hasta el 30, extraer los elementos pares del arreglo generado.

In [ ]:
a2_np = np.arange(10, 31)
ar2_np_pares = a2_np[a2_np % 2 == 0]
print(ar2_np_pares)

[10 12 14 16 18 20 22 24 26 28 30]


5) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [ ]:
a3_np = np.arange(10, 31)
for i in range(len(a3_np)):
    if a3_np[i] % 2 == 0:
        a3_np[i] = -1
print(a3_np)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


6) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [ ]:
a4_np = np.arange(10, 31)
a4_np[a4_np % 2 == 0] = -1
print(a4_np)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


7) Reemplazar todos los números pares por -1 y por 0 los impares de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [ ]:
a5_np = np.arange(10, 31)
print("Arreglo original:", a5_np)
for i in range(len(a5_np)):
    if a5_np[i] % 2 == 0:
        if 10 <= a5_np[i] <= 30:
            a5_np[i] = -1
    else:
        if 10 <= a5_np[i] <= 30:
            a5_np[i] = 0
print("Arreglo modificado:", a5_np)

Arreglo original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Arreglo modificado: [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]


8) Reemplazar todos los números pares por -1 y los impares por 0 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [ ]:
a6_np = np.arange(10, 31)
print("Arreglo original:", a6_np)
arr_modificado = np.where(
    (a6_np >= 10) & (a6_np <= 30),
    np.where(a6_np % 2 == 0, -1, 0),
    a6_np)
print("Arreglo modificado:", arr_modificado)

Arreglo original: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Arreglo modificado: [-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
